# Generated by Django 6.0.6 on 2026-06-23 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên đề thi')),
                ('duration', models.IntegerField(help_text='Thời gian làm bài bằng số phút', verbose_name='Thời gian (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('option_a', models.CharField(max_length=255, verbose_name='Đáp án A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Đáp án B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Đáp án C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Đáp án D')),
                ('correct_option', models.CharField(choices=[('A', 'Đáp án A'), ('B', 'Đáp án B'), ('C', 'Đáp án C'), ('D', 'Đáp án D')], max_length=1, verbose_name='Đáp án đúng')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.exam', verbose_name='Thuộc đề thi')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(verbose_name='Số câu đúng')),
                ('total_questions', models.IntegerField(verbose_name='Tổng số câu')),
                ('score', models.FloatField(verbose_name='Điểm số')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nộp bài')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Đề thi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học sinh')),
            ],
        ),
    ]
