# Generated by Django 6.0.6 on 2026-06-25 06:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_result_options_exam_end_date_exam_max_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConstraintPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên mẫu cấu hình')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả mẫu')),
                ('default_duration', models.PositiveIntegerField(default=60, verbose_name='Thời gian mặc định (phút)')),
                ('default_max_attempts', models.PositiveIntegerField(default=1, verbose_name='Số lượt làm mặc định')),
                ('default_passing_percentage', models.PositiveIntegerField(default=50, verbose_name='Phần trăm đạt mặc định')),
                ('default_show_timer', models.BooleanField(default=True, verbose_name='Bật bộ đếm thời gian')),
                ('default_show_score', models.BooleanField(default=True, verbose_name='Hiện điểm')),
                ('default_show_correct_answers', models.BooleanField(default=True, verbose_name='Hiện đáp án đúng')),
                ('default_allow_review', models.BooleanField(default=True, verbose_name='Cho phép xem lại')),
            ],
            options={
                'verbose_name': 'Mẫu cấu hình sẵn',
                'verbose_name_plural': 'Các mẫu cấu hình sẵn',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
        migrations.RemoveField(
            model_name='result',
            name='teacher_feedback',
        ),
        migrations.AddField(
            model_name='exam',
            name='allow_review',
            field=models.BooleanField(default=True, verbose_name='Cho phép học sinh xem lại bài làm sau nộp'),
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả đề thi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Công khai đề thi ngay'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Học sinh cần bao nhiêu % để đạt điểm qua', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm đạt yêu cầu (%)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='password_protect',
            field=models.CharField(blank=True, help_text='Để trống nếu công khai', max_length=50, null=True, verbose_name='Mật khẩu vào thi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_correct_answers',
            field=models.BooleanField(default=True, verbose_name='Hiển thị đáp án đúng sau khi nộp'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_score',
            field=models.BooleanField(default=True, verbose_name='Hiển thị điểm số cho học sinh'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_timer',
            field=models.BooleanField(default=True, verbose_name='Hiển thị bộ đếm thời gian'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên'),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_warning_minutes',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Cảnh báo thời gian còn lại (phút)'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự câu hỏi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số lượt làm bài tối đa'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='randomize_options',
            field=models.BooleanField(default=False, verbose_name='Xáo trộn các lựa chọn đáp án'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, verbose_name='Xáo trộn câu hỏi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='result',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Lượt làm bài số'),
        ),
        migrations.AlterField(
            model_name='result',
            name='randomization_seed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hạt giống xáo trộn'),
        ),
        migrations.CreateModel(
            name='ExamGradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_a_min', models.IntegerField(default=90, verbose_name='Điểm A tối thiểu (%)')),
                ('grade_b_min', models.IntegerField(default=80, verbose_name='Điểm B tối thiểu (%)')),
                ('grade_c_min', models.IntegerField(default=70, verbose_name='Điểm C tối thiểu (%)')),
                ('grade_d_min', models.IntegerField(default=60, verbose_name='Điểm D tối thiểu (%)')),
                ('grade_f_min', models.IntegerField(default=0, verbose_name='Điểm F tối thiểu (%)')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_rule', to='quiz.exam')),
            ],
            options={
                'verbose_name': 'Quy tắc chấm điểm',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions_in_pool', models.IntegerField(verbose_name='Tổng câu hỏi trong pool')),
                ('questions_to_select', models.IntegerField(verbose_name='Số câu hỏi để chọn ngẫu nhiên')),
                ('use_pool', models.BooleanField(default=False, verbose_name='Sử dụng pool ngẫu nhiên')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_pool', to='quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
